### ISSUE TITLE
GVX missing after redirect causing GVN to not log in.

### ISSUE THREAD

**Issue by Corruptinglyneedful** [davuxcom/GVNotifierWPF#12]
This is the error message I am getting in the log.txt file.

10:38:26 PM: Cannot login: GVX is missing after redirect
10:38:26 PM: Login Failed: GoogleVoice.GVLoginException: GVX is missing after redirect
   at GoogleVoice.Account.Login()
   at GVNotifier.SessionModel.<Login>b__20()

Not a clue how to fix this and I very, very, heavily rely on this program to work.

**Comment by Impr0ve** [comment]
I have the same problem just starting happening don't know why just noticed it today

**Comment by Corruptinglyneedful** [comment]
Still not working today.

I absolutely rely on this program to text people.

It needs to work or someone needs to list an alternative.

**Comment by rkoffler** [comment]
Same

**Comment by JimBlankenship** [comment]
This problem started happening yesterday. I suppose Google changed GVX cookies so that it broke GVNotifier.

Before the "GVX is missing after redirect" error, the log shows an XML error.

17:40:28: GoogleVoice/ContactsManager/ System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read4_ArrayOfContact()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at GoogleVoice.ContactsManager..ctor(String ImageDir, String UserName, HttpSession http)

Sometimes the XML error shows up like this instead:

17:56:50: DavuxLib2/Settings/Get<?> Can't Save: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderGVCookie.Read3_GVCookie()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at DavuxLib2.Extensions.ObjectExtensions.FromXML[T](String str)
   at DavuxLib2.Settings.Get[T](String key, T def)

**Comment by Corruptinglyneedful** [comment]
So how do I fix it?

**Comment by schleprock** [comment]
well, this sucks. it's now happening to me as well...
guess i'll be looking at the code on github this weekend!

**Comment by Corruptinglyneedful** [comment]
Well I got sick and tired of waiting for the developer to fix his busted shit so I went and got the Google Hangouts Chrome App.

I can get so much more from this, than I ever could with GVN.

It uses Chrome, but in the background.  I can use it on Wlindows desktop, without having to actually use Chrome.  It's great.

I should have switched over long ago.

On a side note.  I'm getting really, really, REALLY sick and tired of people abandoning their projects.  If you aren't going to work on it anymore, you need to officially shut it down or pass the torch.  This stringing people along and leaving them hanging shit, needs to stop.

**Comment by schleprock** [comment]
it looks like the hangouts app for chrome only shows SMS messages if you
check the receive SMS in hangouts box. i tried receiving SMS messages in
hangouts a couple years ago and it did not work very well, at all....
can you still get notifications if you don't check the box?

**Comment by Corruptinglyneedful** [comment]
In order to get SMS from Google voice, you need to set up both Google Voice and Hangouts to send to Hangouts.

Google has a help page that can help you do this.

You get offline messages but messages will no longer show up on the Google Voice page, which is fine, IMO.  It's severely limited.

In order to add contacts or edit them, you have to use Google Contacts, much like with GVN.

**Comment by JimBlankenship** [comment]
I found this on SourceForge for GoogleVoice.NET:

"As an FYI, apparently as of June or July 2016 Google appears to have removed support for a good portion of the GV account login handling via URL's and outside of OAuth. And Google's OAuth doesn't appear to include Google Voice as a listed app via their GoogleApis.Com listings...."

https://sourceforge.net/p/gvoicedotnet/discussion/1046696/thread/523adde6/?limit=25#2eab

**Comment by Corruptinglyneedful** [comment]
I don't understand what any of that means.

And even if that was the source, it does not explain why it continued to exist way outside the protocol time.

Which was 15 days ago vs that post of July 2016.
